version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: whatsapp-chatbot-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=whatsapp_chatbot
    networks:
      - whatsapp-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: whatsapp-chatbot-pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - whatsapp-network
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: whatsapp-chatbot-backend
    ports:
      - "5000:80"
    volumes:
      - ./backend:/app
    networks:
      - whatsapp-network
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=whatsapp_chatbot;Username=postgres;Password=postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: whatsapp-chatbot-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - whatsapp-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  postgres_data:
  pgadmin_data:


networks:
  whatsapp-network:
    driver: bridge
