version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: whatsapp-chatbot-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=whatsapp_chatbot
    networks:
      - whatsapp-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: whatsapp-chatbot-pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - whatsapp-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  whatsapp-network:
    driver: bridge 